<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <script src="./promise.js"></script>
  </head>
  <body>
    <script>
      let p = new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve("OK!");
          // reject("err");
        }, 1000);
        // throw "error";
      });
      p.then(
        (value) => {
          return new Promise((resolve, reject) => {
            console.log(2);
          });
        },
        (reason) => {
          console.log(reason);
        }
      ).then((value) => {
        console.log(value);
        return new Promise(() => {}); //使用该方法可以将一个链式的Promise中止
      });
      //   .then((value) => {
      //     console.log(222);
      //   })
      //   .catch((reasoe) => {
      //     //异常穿透 链式调用中如果失败的话会直接调用到这个函数
      //     console.error(reasoe);
      //   });
    </script>
  </body>
</html>
